# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/haas/Desktop/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.srcs/sources_1/ip/convFC_weights/convFC_weights.xci
# IP: The module: 'convFC_weights' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/haas/Desktop/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/convFC_weights/convFC_weights_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'convFC_weights'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/haas/Desktop/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.srcs/sources_1/ip/convFC_weights/convFC_weights.xci
# IP: The module: 'convFC_weights' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/haas/Desktop/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/convFC_weights/convFC_weights_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'convFC_weights'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
