# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/synth_1/cnn_top_tb.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param checkpoint.writeSynthRtdsInDcp 1
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-1870350-leds-inspiron3020/incrSyn
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.cache/wt [current_project]
set_property parent.project_path /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zc702:part0:1.4 [current_project]
set_property ip_output_repo /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/input_img/A_input_chanel_R.coe
add_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/input_img/A_input_chanel_G.coe
add_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/input_img/A_input_chanel_B.coe
add_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/conv1_bias.coe
add_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/conv1.coe
add_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/conv2_bias.coe
add_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/conv2.coe
add_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/conv3_bias.coe
add_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/conv3.coe
add_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/conv4_bias.coe
add_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/conv4.coe
add_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/fc_bias.coe
add_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/fc.coe
add_files -quiet /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/convFC_bias/convFC_bias.dcp
set_property used_in_implementation false [get_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/convFC_bias/convFC_bias.dcp]
add_files -quiet /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/convFC_weights_synth_1/convFC_weights.dcp
set_property used_in_implementation false [get_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/convFC_weights_synth_1/convFC_weights.dcp]
add_files -quiet /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/generic_ram_synth_1/generic_ram.dcp
set_property used_in_implementation false [get_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/generic_ram_synth_1/generic_ram.dcp]
add_files -quiet /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/conv4_bias_synth_1/conv4_bias.dcp
set_property used_in_implementation false [get_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/conv4_bias_synth_1/conv4_bias.dcp]
add_files -quiet /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/conv4_weights_synth_1/conv4_weights.dcp
set_property used_in_implementation false [get_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/conv4_weights_synth_1/conv4_weights.dcp]
add_files -quiet /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/conv3_bias_synth_1/conv3_bias.dcp
set_property used_in_implementation false [get_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/conv3_bias_synth_1/conv3_bias.dcp]
add_files -quiet /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/conv3_weights_synth_1/conv3_weights.dcp
set_property used_in_implementation false [get_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/conv3_weights_synth_1/conv3_weights.dcp]
add_files -quiet /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/conv1_bias_synth_1/conv1_bias.dcp
set_property used_in_implementation false [get_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/conv1_bias_synth_1/conv1_bias.dcp]
add_files -quiet /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/conv1_weights_synth_1/conv1_weights.dcp
set_property used_in_implementation false [get_files /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.runs/conv1_weights_synth_1/conv1_weights.dcp]
read_mem {
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/input_img/A_input_chanel_R.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/fc_bias.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/fc.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/mif_files/conv3_bias.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/mif_files/conv1.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/mif_files/conv3.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/conv4_bias.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/mif_files/conv2.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/conv1_bias.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/mif_files/conv4_bias.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/conv4.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/conv3.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/conv2_bias.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/input_img/A_input_chanel_G.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/conv2.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/input_img/Y_input_chanel_R.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/mif_files/fc_bias.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/conv3_bias.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/input_img/Y_input_chanel_G.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/conv1.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/mif_files/fc.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/mif_files/conv2_bias.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/mif_files/conv4.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/input_img/A_input_chanel_B.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/weights_and_biases/mif_files/conv1_bias.mif
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/input_img/Y_input_chanel_B.mif
}
read_vhdl -library xil_defaultlib {
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/conv1_bias/conv1_bias_stub.vhdl
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/conv1_weights/conv1_weights_stub.vhdl
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/conv3_bias/conv3_bias_stub.vhdl
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/conv3_weights/conv3_weights_stub.vhdl
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/conv4_bias/conv4_bias_stub.vhdl
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/conv4_weights/conv4_weights_stub.vhdl
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/convFC_bias/convFC_bias_stub.vhdl
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/convFC_weights/convFC_weights_stub.vhdl
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/generic_ram/generic_ram_stub.vhdl
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/add1.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/add32.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/arvore_comparadores.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/arvore_soma_conv.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/types_pkg.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_top.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/conv1.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/conv1_crt.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/conv1_op.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/conv2.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/conv3.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/conv4.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/counter.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/demux_1x4.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/fc.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/fc_crt.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/fc_op.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/generic_demultiplexer.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/generic_multiplexer.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/io_buffer.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/max_pooling.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/multiplicador_conv.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/neuronio.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/nucleo_convolucional.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/one_hot_encoder.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/pool1.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/pool1_crt.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/pool1_op.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/rebuff1.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/rebuffer_crt.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/rebuffer_op.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/registrador.vhd
  /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_top_tb.vhd
}
read_ip -quiet /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.srcs/sources_1/ip/conv2_bias/conv2_bias.xci
set_property used_in_implementation false [get_files -all /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/conv2_bias/conv2_bias_ooc.xdc]

read_ip -quiet /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.srcs/sources_1/ip/conv2_weights/conv2_weights.xci
set_property used_in_implementation false [get_files -all /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/conv2_weights/conv2_weights_ooc.xdc]

read_ip -quiet /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.srcs/sources_1/ip/image_chanel_0/image_chanel_0.xci
set_property used_in_implementation false [get_files -all /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/image_chanel_0/image_chanel_0_ooc.xdc]

read_ip -quiet /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.srcs/sources_1/ip/image_chanel_1/image_chanel_1.xci
set_property used_in_implementation false [get_files -all /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/image_chanel_1/image_chanel_1_ooc.xdc]

read_ip -quiet /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.srcs/sources_1/ip/image_chanel_2/image_chanel_2.xci
set_property used_in_implementation false [get_files -all /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/image_chanel_2/image_chanel_2_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top cnn_top_tb -part xc7z020clg484-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cnn_top_tb.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file cnn_top_tb_utilization_synth.rpt -pb cnn_top_tb_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
