# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-2000424-leds-inspiron3020/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    set rt::enableVHDL2008 1
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib xil_defaultlib {
      ./.Xil/Vivado-2000424-leds-inspiron3020/realtime/convFC_bias_stub.vhdl
      ./.Xil/Vivado-2000424-leds-inspiron3020/realtime/convFC_weights_stub.vhdl
      ./.Xil/Vivado-2000424-leds-inspiron3020/realtime/generic_ram_stub.vhdl
      ./.Xil/Vivado-2000424-leds-inspiron3020/realtime/conv4_bias_stub.vhdl
      ./.Xil/Vivado-2000424-leds-inspiron3020/realtime/conv4_weights_stub.vhdl
      ./.Xil/Vivado-2000424-leds-inspiron3020/realtime/conv3_bias_stub.vhdl
      ./.Xil/Vivado-2000424-leds-inspiron3020/realtime/conv3_weights_stub.vhdl
      ./.Xil/Vivado-2000424-leds-inspiron3020/realtime/conv1_bias_stub.vhdl
      ./.Xil/Vivado-2000424-leds-inspiron3020/realtime/conv1_weights_stub.vhdl
      ./.Xil/Vivado-2000424-leds-inspiron3020/realtime/conv2_bias_stub.vhdl
      ./.Xil/Vivado-2000424-leds-inspiron3020/realtime/conv2_weights_stub.vhdl
      ./.Xil/Vivado-2000424-leds-inspiron3020/realtime/image_chanel_0_stub.vhdl
      ./.Xil/Vivado-2000424-leds-inspiron3020/realtime/image_chanel_1_stub.vhdl
      ./.Xil/Vivado-2000424-leds-inspiron3020/realtime/image_chanel_2_stub.vhdl
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/conv1_bias/conv1_bias_stub.vhdl
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/conv1_weights/conv1_weights_stub.vhdl
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/conv3_bias/conv3_bias_stub.vhdl
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/conv3_weights/conv3_weights_stub.vhdl
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/conv4_bias/conv4_bias_stub.vhdl
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/conv4_weights/conv4_weights_stub.vhdl
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/convFC_bias/convFC_bias_stub.vhdl
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/convFC_weights/convFC_weights_stub.vhdl
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/generic_ram/generic_ram_stub.vhdl
    }
      rt::read_vhdl -vhdl2008 -lib xil_defaultlib {
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/add1.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/add32.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/arvore_comparadores.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/arvore_soma_conv.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/types_pkg.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_top.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/conv1.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/conv1_crt.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/conv1_op.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/conv2.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/conv3.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/conv4.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/counter.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/demux_1x4.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/fc.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/fc_crt.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/fc_op.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/generic_demultiplexer.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/generic_multiplexer.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/io_buffer.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/max_pooling.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/multiplicador_conv.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/neuronio.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/nucleo_convolucional.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/one_hot_encoder.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/pool1.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/pool1_crt.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/pool1_op.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/rebuff1.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/rebuffer_crt.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/rebuffer_op.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/registrador.vhd
      /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_top_tb.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-2000424-leds-inspiron3020/realtime/cnn_top_tb_synth.xdc
    rt::sdcChecksum
    set rt::top cnn_top_tb
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-2000424-leds-inspiron3020/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
