# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.srcs/sources_1/ip/image_chanel_1/image_chanel_1.xci
# IP: The module: 'image_chanel_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/image_chanel_1/image_chanel_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_chanel_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.srcs/sources_1/ip/image_chanel_1/image_chanel_1.xci
# IP: The module: 'image_chanel_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/image_chanel_1/image_chanel_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_chanel_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
