# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.srcs/sources_1/ip/conv4_bias/conv4_bias.xci
# IP: The module: 'conv4_bias' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/conv4_bias/conv4_bias_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv4_bias'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.srcs/sources_1/ip/conv4_bias/conv4_bias.xci
# IP: The module: 'conv4_bias' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/haas/Documents/GitHub/cnn_hardware_accelerator_XILINX/cnn_hardware_accelerator_VIVADO/cnn_hardware_accelerator_VIVADO.gen/sources_1/ip/conv4_bias/conv4_bias_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv4_bias'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
